### ISSUE TITLE
[BUG] pls suppress this

### ISSUE THREAD

**Issue by leestarb** [meth1337/rice-clock#1]
when pressing ^C:

```
Traceback (most recent call last):
  File "clock.py", line 39, in <module>
  File "clock.py", line 32, in clock
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "clock.py", line 54, in <module>
KeyboardInterrupt
[7382] Failed to execute script 'clock' due to unhandled exception!
```

the screen doesnt reset

running from the latest binaries

**Comment by leestarb** [comment]
not sure why this happen

**Comment by meth1337** [comment]
Should be fixed now. https://github.com/meth1337/rice-clock/blob/main/rice-clock
Pls update your binary by downloading it from https://github.com/meth1337/rice-clock/blob/main/rice-clock

**Comment by leestarb** [comment]
@meth1337 
This hasnt been fixed in 1.2.2
```
^CTraceback (most recent call last):
  File "clock.py", line 75, in <module>
  File "clock.py", line 41, in clock_12h
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "clock.py", line 75, in <module>
KeyboardInterrupt
[5062] Failed to execute script 'clock' due to unhandled exception!
```

**Comment by meth1337** [comment]
well, i'll fix it as i'll know how..

**Comment by leestarb** [comment]
I found needed fix in #4

**Comment by leestarb** [comment]
Wow it works! Thats a great fix, thanks!
